export type GlossaryCategory =
  | "게임 진행"
  | "터미널과 파일"
  | "Git과 GitHub"
  | "Vim 편집"
  | "코딩 기본"
  | "데이터와 비동기"
  | "웹과 React"
  | "AI와 제품 품질";

export type GlossarySource =
  | "CodeQuest"
  | "App Factory"
  | "MDN"
  | "Git"
  | "Python"
  | "React";

export type GlossaryEntry = {
  term: string;
  category: GlossaryCategory;
  aliases: string[];
  short: string;
  analogy: string;
  useWhen: string;
  caution: string;
  related: string[];
  sources: GlossarySource[];
};

export const GLOSSARY_CATEGORIES: readonly GlossaryCategory[] = [
  "게임 진행",
  "터미널과 파일",
  "Git과 GitHub",
  "Vim 편집",
  "코딩 기본",
  "데이터와 비동기",
  "웹과 React",
  "AI와 제품 품질",
];

export const GLOSSARY_SOURCE_LABELS: Record<GlossarySource, string> = {
  CodeQuest: "CodeQuest 미션 콘텐츠",
  "App Factory": "App Factory 용어사전 패턴",
  MDN: "MDN Web Docs Glossary",
  Git: "Git 공식 glossary/manpage",
  Python: "Python 공식 Glossary",
  React: "React 공식 문서",
};

export const GLOSSARY_SOURCE_URLS: Record<GlossarySource, string | null> = {
  CodeQuest: null,
  "App Factory": null,
  MDN: "https://developer.mozilla.org/en-US/docs/Glossary",
  Git: "https://git-scm.com/docs/gitglossary",
  Python: "https://docs.python.org/3/glossary.html",
  React: "https://react.dev/learn",
};

export const GLOSSARY_ENTRIES: readonly GlossaryEntry[] = [
  {
    term: "미션",
    category: "게임 진행",
    aliases: ["퀘스트", "스테이지", "문제"],
    short: "하나의 학습 목표를 이야기, 실습, 보상으로 묶은 단위.",
    analogy: "놀이공원의 한 놀이기구다. 줄을 서고, 타고, 끝나면 도장을 받는다.",
    useWhen: "새 명령이나 개념을 작은 성공 경험으로 나눠 배울 때.",
    caution: "미션을 빨리 끝내는 것보다 왜 그 명령이 필요한지 말로 설명할 수 있어야 한다.",
    related: ["Step", "XP", "보스"],
    sources: ["CodeQuest"],
  },
  {
    term: "Step",
    category: "게임 진행",
    aliases: ["단계", "장면"],
    short: "미션 안에서 대화, 터미널, 코드 실습처럼 한 번에 진행하는 작은 장면.",
    analogy: "요리 레시피의 한 줄이다. 재료 준비, 썰기, 굽기가 따로 적혀 있다.",
    useWhen: "큰 미션을 너무 어렵지 않게 순서대로 안내할 때.",
    caution: "이전 Step의 상태가 다음 Step과 이어지는지 확인해야 이야기가 끊기지 않는다.",
    related: ["미션", "힌트", "NPC 조언"],
    sources: ["CodeQuest"],
  },
  {
    term: "XP",
    category: "게임 진행",
    aliases: ["경험치", "보상 점수"],
    short: "미션을 완료했을 때 성장도를 보여주는 점수.",
    analogy: "운동 기록장에 붙는 스티커다. 많이 붙을수록 꾸준히 훈련했다는 뜻이다.",
    useWhen: "학습자가 진행 중이라는 감각을 얻고 다음 영역을 열 때.",
    caution: "XP가 이해도를 보장하지는 않는다. 복습 미션과 설명 카드가 함께 필요하다.",
    related: ["레벨", "뱃지", "미션"],
    sources: ["CodeQuest"],
  },
  {
    term: "레벨",
    category: "게임 진행",
    aliases: ["Lv", "잠금 해제 기준"],
    short: "학습 진행에 따라 새 영역을 열어 주는 단계.",
    analogy: "도서관 출입증 등급이다. 기본 서가를 읽으면 더 깊은 서가가 열린다.",
    useWhen: "초보자가 너무 어려운 미션을 먼저 만나지 않도록 경로를 조절할 때.",
    caution: "레벨 제한은 안내 장치여야지 막다른 벽이 되면 안 된다.",
    related: ["XP", "영역", "미션"],
    sources: ["CodeQuest"],
  },
  {
    term: "영역",
    category: "게임 진행",
    aliases: ["Realm", "월드", "대륙"],
    short: "터미널, Vim, Git, Python처럼 비슷한 학습 주제를 묶은 세계.",
    analogy: "학교의 과목 교실이다. 과학실, 음악실, 체육관마다 배우는 도구가 다르다.",
    useWhen: "학습 주제를 MECE하게 나눠 길을 잃지 않게 만들 때.",
    caution: "영역이 너무 많으면 지도는 커지지만 길은 흐려진다. 겹치는 주제는 합쳐야 한다.",
    related: ["미션", "레벨", "월드맵"],
    sources: ["CodeQuest", "App Factory"],
  },
  {
    term: "보스",
    category: "게임 진행",
    aliases: ["Boss", "종합 미션"],
    short: "앞에서 배운 여러 개념을 한 번에 묶어 확인하는 큰 미션.",
    analogy: "단원평가다. 새 문제를 내지만, 재료는 전부 지난 수업에서 배운 것이다.",
    useWhen: "학습자가 개별 명령을 외운 것이 아니라 조합할 수 있는지 확인할 때.",
    caution: "보스는 어렵되 불공평하면 안 된다. 직전 미션에서 필요한 조각을 모두 연습해야 한다.",
    related: ["미션", "복습", "힌트"],
    sources: ["CodeQuest"],
  },
  {
    term: "힌트",
    category: "게임 진행",
    aliases: ["도움말", "정답 유도"],
    short: "막혔을 때 다음 행동을 좁혀 주는 짧은 안내.",
    analogy: "보물찾기에서 주는 방향표다. 보물 위치를 통째로 말하지 않고 길을 틔워 준다.",
    useWhen: "학습자가 같은 실패를 반복해 좌절하기 전에.",
    caution: "힌트가 곧 정답이 되면 사고 과정이 사라진다. 처음에는 이유를, 나중에는 명령을 보여준다.",
    related: ["NPC 조언", "Step", "미션"],
    sources: ["CodeQuest", "App Factory"],
  },
  {
    term: "NPC 조언",
    category: "게임 진행",
    aliases: ["코치 패널", "파인만 설명"],
    short: "명령이나 개념을 쉬운 비유, 쓰임, 주의점으로 풀어 주는 설명 카드.",
    analogy: "옆자리 선배가 어려운 말을 초등학생도 아는 물건에 빗대어 설명해 주는 순간이다.",
    useWhen: "새 용어가 나왔는데 왜 쓰는지 모를 때.",
    caution: "비유는 입구일 뿐이다. 실제 명령의 정확한 동작은 실습으로 확인해야 한다.",
    related: ["힌트", "용어 사전", "파인만 기법"],
    sources: ["CodeQuest", "App Factory"],
  },
  {
    term: "터미널",
    category: "터미널과 파일",
    aliases: ["Shell", "CLI", "명령줄"],
    short: "글자로 컴퓨터에 명령을 보내는 작업 공간.",
    analogy: "마우스 대신 주문을 적는 창구다. 짧은 문장을 쓰면 컴퓨터가 바로 처리한다.",
    useWhen: "파일 이동, Git, 서버 실행, 개발 도구 실행을 빠르게 처리할 때.",
    caution: "현재 위치와 명령 대상이 맞는지 먼저 확인해야 한다.",
    related: ["pwd", "cd", "ls", "명령"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "명령",
    category: "터미널과 파일",
    aliases: ["Command", "주문"],
    short: "터미널에 입력하는 실행 지시.",
    analogy: "자판기 버튼이다. 버튼 이름과 옵션을 정확히 눌러야 원하는 음료가 나온다.",
    useWhen: "컴퓨터에게 파일을 만들거나 이동하거나 프로그램을 실행하라고 지시할 때.",
    caution: "비슷해 보이는 명령도 결과가 크게 다를 수 있다. 특히 삭제 명령은 조심한다.",
    related: ["터미널", "옵션", "경로"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "경로",
    category: "터미널과 파일",
    aliases: ["Path", "파일 위치"],
    short: "파일이나 폴더가 어디에 있는지 나타내는 주소.",
    analogy: "건물 안 방 번호다. 몇 층, 어느 복도, 어떤 방인지 적어 둔 주소다.",
    useWhen: "파일을 읽고, 옮기고, 저장하고, 실행할 위치를 지정할 때.",
    caution: "절대 경로와 상대 경로를 헷갈리면 엉뚱한 방으로 간다.",
    related: ["pwd", "cd", "폴더"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "pwd",
    category: "터미널과 파일",
    aliases: ["현재 위치"],
    short: "현재 터미널이 보고 있는 폴더 위치를 출력하는 명령.",
    analogy: "미로 지도에서 '나는 여기' 점을 보는 일이다.",
    useWhen: "파일을 만들거나 Git 명령을 실행하기 전에 위치를 확인할 때.",
    caution: "위치가 틀리면 맞는 명령도 틀린 곳에 적용된다.",
    related: ["터미널", "경로", "cd"],
    sources: ["CodeQuest"],
  },
  {
    term: "ls",
    category: "터미널과 파일",
    aliases: ["목록 보기", "list"],
    short: "현재 폴더의 파일과 폴더 목록을 보여주는 명령.",
    analogy: "가방을 열어 안에 든 물건 이름을 확인하는 일이다.",
    useWhen: "무엇이 있는지 먼저 둘러볼 때. 숨김 파일은 `ls -a`로 본다.",
    caution: "목록만 보여준다. 파일 내용까지 읽는 명령은 아니다.",
    related: ["숨김 파일", "폴더", "터미널"],
    sources: ["CodeQuest"],
  },
  {
    term: "숨김 파일",
    category: "터미널과 파일",
    aliases: ["dotfile", ".파일"],
    short: "이름이 점으로 시작해 기본 목록에서 숨겨지는 설정 파일.",
    analogy: "책장 뒤쪽에 붙은 작은 메모다. 평소엔 안 보이지만 중요한 규칙이 적혀 있다.",
    useWhen: ".git, .env, .gitignore처럼 도구 설정을 다룰 때.",
    caution: "숨김 파일에는 민감 정보가 있을 수 있다. 공개 저장소에 올리기 전에 확인한다.",
    related: ["ls", ".git", ".gitignore"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "cd",
    category: "터미널과 파일",
    aliases: ["폴더 이동", "change directory"],
    short: "터미널의 현재 폴더를 바꾸는 명령.",
    analogy: "작업할 방으로 걸어 들어가는 행동이다.",
    useWhen: "특정 프로젝트 폴더 안에서 명령을 실행해야 할 때.",
    caution: "홈 폴더 같은 넓은 위치에서 위험한 명령을 실행하지 않도록 확인한다.",
    related: ["pwd", "경로", "폴더"],
    sources: ["CodeQuest"],
  },
  {
    term: "mkdir",
    category: "터미널과 파일",
    aliases: ["폴더 만들기"],
    short: "새 폴더를 만드는 명령.",
    analogy: "책장에 새 칸을 만드는 일이다.",
    useWhen: "프로젝트, 자료, 결과물을 분리해서 보관할 공간이 필요할 때.",
    caution: "이미 같은 이름이 있으면 실패할 수 있다. 만든 뒤 `ls`로 확인한다.",
    related: ["폴더", "경로", "터미널"],
    sources: ["CodeQuest"],
  },
  {
    term: "mv",
    category: "터미널과 파일",
    aliases: ["이동", "이름 바꾸기"],
    short: "파일을 옮기거나 이름을 바꾸는 명령.",
    analogy: "책상 위 물건을 다른 서랍으로 옮기거나 이름표를 새로 붙이는 일이다.",
    useWhen: "파일을 정리하거나 결과물을 원하는 폴더로 이동할 때.",
    caution: "복사가 아니라 이동이다. 원래 위치에서는 사라질 수 있다.",
    related: ["경로", "파일", "폴더"],
    sources: ["CodeQuest"],
  },
  {
    term: "rm",
    category: "터미널과 파일",
    aliases: ["삭제", "remove"],
    short: "파일을 삭제하는 명령.",
    analogy: "되돌리기 버튼이 없는 휴지통에 버리는 일이다.",
    useWhen: "정말 필요 없는 파일만 지울 때.",
    caution: "실제 터미널에서는 매우 조심한다. 경로와 파일명을 먼저 확인한다.",
    related: ["터미널", "경로", "rm -rf"],
    sources: ["CodeQuest"],
  },
  {
    term: "Git",
    category: "Git과 GitHub",
    aliases: ["버전 관리", "시간 기록"],
    short: "파일 변경 이력을 저장하고 되돌릴 수 있게 하는 도구.",
    analogy: "프로젝트의 시간 앨범이다. 언제 어떤 페이지를 붙였는지 기록한다.",
    useWhen: "코드 변경을 안전하게 기록하고 팀과 협업할 때.",
    caution: "Git은 저장소 안의 기록을 관리한다. 저장소 위치를 잘못 잡으면 원치 않는 파일이 잡힌다.",
    related: ["Repository", "Commit", "Branch"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Repository",
    category: "Git과 GitHub",
    aliases: ["repo", "저장소"],
    short: "Git이 변경 이력을 관리하는 프로젝트 폴더.",
    analogy: "앨범과 사진 보관함을 합친 상자다. 사진도 있고 붙인 기록도 있다.",
    useWhen: "프로젝트별로 독립된 변경 이력을 만들 때.",
    caution: "저장소를 너무 큰 폴더에 만들면 개인 파일까지 상태에 잡힐 수 있다.",
    related: ["Git", "git init", ".git"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: ".git",
    category: "Git과 GitHub",
    aliases: ["Git 내부 폴더"],
    short: "Git 저장소의 기록과 설정이 들어 있는 숨김 폴더.",
    analogy: "앨범 뒤쪽의 비밀 장부다. 겉으로 보이는 사진보다 중요한 기록이 들어 있다.",
    useWhen: "Git 저장소가 어디에 만들어졌는지 이해할 때.",
    caution: "함부로 삭제하거나 수정하지 않는다. 잘못 만들었을 때만 위치를 확인하고 제거한다.",
    related: ["Repository", "git init", "숨김 파일"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "git init",
    category: "Git과 GitHub",
    aliases: ["저장소 초기화"],
    short: "현재 폴더를 Git 저장소로 만드는 명령.",
    analogy: "평범한 폴더에 시간 기록 장부를 펼치는 순간이다.",
    useWhen: "새 프로젝트의 변경 이력을 처음 기록하기 시작할 때.",
    caution: "반드시 프로젝트 폴더 안에서 실행한다.",
    related: ["Repository", ".git", "main"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "git status",
    category: "Git과 GitHub",
    aliases: ["상태 보기"],
    short: "현재 변경 파일과 stage 상태를 확인하는 명령.",
    analogy: "요리 전 재료판이다. 빨간 재료는 밖에 있고 초록 재료는 냄비 옆에 있다.",
    useWhen: "add, commit, push 전 무엇이 바뀌었는지 확인할 때.",
    caution: "빨간 파일은 아직 커밋 후보가 아니다. 초록 파일만 다음 커밋에 들어간다.",
    related: ["Working tree", "Staging area", "git add"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Working tree",
    category: "Git과 GitHub",
    aliases: ["작업 트리", "작업 폴더"],
    short: "현재 실제 파일들이 놓여 있고 수정되는 공간.",
    analogy: "사진을 자르고 붙이는 작업대다. 아직 앨범에 붙인 것은 아니다.",
    useWhen: "파일을 직접 수정하고 Git이 그 변화를 감지할 때.",
    caution: "작업 트리 상태를 보지 않고 commit/push하면 원치 않는 변경이 섞일 수 있다.",
    related: ["git status", "Staging area", "Commit"],
    sources: ["Git"],
  },
  {
    term: "Staging area",
    category: "Git과 GitHub",
    aliases: ["stage", "index", "초록 상태"],
    short: "다음 커밋에 넣을 변경을 임시로 고르는 공간.",
    analogy: "앨범에 붙일 사진을 먼저 담는 바구니다.",
    useWhen: "여러 변경 중 일부만 골라 의미 있는 커밋을 만들 때.",
    caution: "stage에 올렸다고 기록이 끝난 것은 아니다. commit이 필요하다.",
    related: ["git add", "Commit", "git status"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "git add",
    category: "Git과 GitHub",
    aliases: ["stage 올리기"],
    short: "변경 파일을 staging area에 올리는 명령.",
    analogy: "앨범 후보 사진을 바구니에 담는 일이다.",
    useWhen: "다음 커밋에 포함할 파일을 선택할 때.",
    caution: "`git add .`는 많은 파일을 한꺼번에 담는다. 민감 정보와 빌드 산출물을 확인한다.",
    related: ["Staging area", "git status", "Commit"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Commit",
    category: "Git과 GitHub",
    aliases: ["커밋", "스냅샷"],
    short: "선택한 변경을 메시지와 함께 저장한 기록.",
    analogy: "앨범 한 페이지를 붙이고 제목을 적는 일이다.",
    useWhen: "작업 단위가 의미 있게 끝났을 때 되돌아갈 지점을 남긴다.",
    caution: "커밋 메시지는 나중에 읽는 사람도 이해할 수 있어야 한다.",
    related: ["git commit", "git log", "Staging area"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Branch",
    category: "Git과 GitHub",
    aliases: ["브랜치", "작업 가지"],
    short: "main과 분리해 독립적으로 작업하는 Git의 흐름.",
    analogy: "원본 그림 옆에 새 스케치북을 펼치는 일이다.",
    useWhen: "새 기능, 실험, 버그 수정을 main과 분리해서 진행할 때.",
    caution: "브랜치를 바꾸기 전 커밋하지 않은 변경이 있는지 확인한다.",
    related: ["main", "git switch", "Merge"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Merge",
    category: "Git과 GitHub",
    aliases: ["병합", "합치기"],
    short: "다른 브랜치의 변경을 현재 브랜치에 합치는 작업.",
    analogy: "두 스케치북의 완성된 그림을 한 책에 붙이는 일이다.",
    useWhen: "feature 브랜치 작업을 main에 반영할 때.",
    caution: "같은 줄을 서로 다르게 고치면 conflict가 날 수 있다.",
    related: ["Branch", "Conflict", "Pull Request"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Conflict",
    category: "Git과 GitHub",
    aliases: ["충돌"],
    short: "Git이 자동으로 합칠 수 없는 서로 다른 변경.",
    analogy: "두 사람이 같은 문장에 서로 다른 답을 적어 선생님이 판단을 요청하는 상황이다.",
    useWhen: "merge 중 같은 파일의 같은 부분이 다르게 수정됐을 때.",
    caution: "둘 중 하나를 기계적으로 고르지 말고 의도를 확인해 사람이 정리한다.",
    related: ["Merge", "git status", "Commit"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Remote",
    category: "Git과 GitHub",
    aliases: ["원격 저장소", "origin"],
    short: "GitHub처럼 네트워크 너머에 있는 저장소 연결.",
    analogy: "택배를 보낼 구름 도서관 주소다.",
    useWhen: "로컬 기록을 백업하거나 팀과 공유할 때.",
    caution: "origin 주소가 틀리면 다른 저장소로 push할 수 있다.",
    related: ["git remote -v", "Push", "GitHub"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Push",
    category: "Git과 GitHub",
    aliases: ["git push", "올리기"],
    short: "로컬 커밋을 원격 저장소로 보내는 작업.",
    analogy: "내 앨범 페이지를 구름 도서관의 같은 책장에 복사해 올리는 일이다.",
    useWhen: "GitHub에 백업하거나 팀원이 내 변경을 볼 수 있게 할 때.",
    caution: "push 전 민감 정보가 커밋에 들어갔는지 확인한다.",
    related: ["Remote", "Commit", "GitHub"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Pull Request",
    category: "Git과 GitHub",
    aliases: ["PR", "리뷰 요청"],
    short: "브랜치 변경을 main에 합치기 전 검토하도록 여는 요청.",
    analogy: "선생님 책상에 스케치북을 올리고 검토 쪽지를 붙이는 일이다.",
    useWhen: "협업에서 코드 리뷰, 테스트, 설명을 거친 뒤 병합할 때.",
    caution: "제목, 설명, 테스트 결과를 남겨야 리뷰가 빠르고 정확해진다.",
    related: ["Branch", "Merge", "GitHub"],
    sources: ["Git", "CodeQuest"],
  },
  {
    term: "Vim",
    category: "Vim 편집",
    aliases: ["빔", "터미널 편집기"],
    short: "키보드 명령 중심의 강력한 텍스트 편집기.",
    analogy: "마우스 대신 검술 자세로 글자를 베고 옮기는 도장이다.",
    useWhen: "서버, Git 커밋 메시지, 설정 파일처럼 터미널 안에서 빠르게 편집할 때.",
    caution: "모드를 이해하지 못하면 글자가 안 써지거나 명령이 안 먹힌다.",
    related: ["Normal mode", "Insert mode", "dd"],
    sources: ["CodeQuest"],
  },
  {
    term: "Normal mode",
    category: "Vim 편집",
    aliases: ["명령 모드", "기본 자세"],
    short: "글자를 입력하지 않고 이동, 삭제, 복사 같은 명령을 내리는 Vim 모드.",
    analogy: "검을 들고 발놀림을 하는 자세다.",
    useWhen: "커서를 움직이고 텍스트를 빠르게 편집할 때.",
    caution: "글자를 쓰려면 Insert mode로 들어가야 한다.",
    related: ["Insert mode", "Esc", "hjkl"],
    sources: ["CodeQuest"],
  },
  {
    term: "Insert mode",
    category: "Vim 편집",
    aliases: ["입력 모드"],
    short: "키를 누르면 실제 글자가 입력되는 Vim 모드.",
    analogy: "검을 내려놓고 붓을 든 상태다.",
    useWhen: "`i`, `a`, `o` 등으로 텍스트를 새로 입력할 때.",
    caution: "입력이 끝나면 `Esc`로 Normal mode로 돌아온다.",
    related: ["Normal mode", "Esc", "i"],
    sources: ["CodeQuest"],
  },
  {
    term: "hjkl",
    category: "Vim 편집",
    aliases: ["Vim 방향키"],
    short: "Vim에서 왼쪽, 아래, 위, 오른쪽으로 이동하는 기본 키.",
    analogy: "검사의 네 방향 발걸음이다.",
    useWhen: "손을 키보드 중심에서 멀리 움직이지 않고 이동할 때.",
    caution: "처음에는 느려도 손이 기억하면 화살표보다 빠르다.",
    related: ["Normal mode", "Vim", "커서"],
    sources: ["CodeQuest"],
  },
  {
    term: "dd",
    category: "Vim 편집",
    aliases: ["줄 삭제"],
    short: "현재 줄 전체를 삭제하는 Vim 명령.",
    analogy: "한 줄을 통째로 베어내는 검술이다.",
    useWhen: "불필요한 줄을 빠르게 지울 때.",
    caution: "대상이 맞는 줄인지 확인한다. 실수하면 `u`로 되돌린다.",
    related: ["u", "dw", "x"],
    sources: ["CodeQuest"],
  },
  {
    term: "매크로",
    category: "Vim 편집",
    aliases: ["macro", "q/@ 반복"],
    short: "편집 동작을 녹화해 여러 번 재생하는 기능.",
    analogy: "내 손동작을 녹음해 작은 조수에게 반복시키는 일이다.",
    useWhen: "비슷한 수정이 여러 줄에 반복될 때.",
    caution: "첫 동작이 틀리면 틀린 행동도 반복된다.",
    related: ["Vim", "반복", "검색치환"],
    sources: ["CodeQuest"],
  },
  {
    term: "검색치환",
    category: "Vim 편집",
    aliases: [":%s/old/new/g", "replace"],
    short: "문서 안의 특정 패턴을 찾아 다른 글자로 바꾸는 편집.",
    analogy: "문서 전체에서 같은 오타 스티커를 찾아 새 스티커로 갈아 붙이는 일이다.",
    useWhen: "반복되는 단어, 접두사, 변수명을 한 번에 바꿀 때.",
    caution: "패턴을 넓게 잡으면 바꾸면 안 되는 글자까지 바뀐다.",
    related: ["Vim", "패턴", "매크로"],
    sources: ["CodeQuest"],
  },
  {
    term: "JavaScript",
    category: "코딩 기본",
    aliases: ["JS", "웹 룬어"],
    short: "웹 브라우저와 서버에서 널리 쓰이는 프로그래밍 언어.",
    analogy: "무대 뒤 조명 기사다. 버튼을 누르면 화면이 즉시 반응하게 만든다.",
    useWhen: "웹 화면, 사용자 이벤트, API 응답 처리를 만들 때.",
    caution: "비동기 처리와 타입 변환에서 예상 밖 결과가 나올 수 있다.",
    related: ["변수", "함수", "React"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "Python",
    category: "코딩 기본",
    aliases: ["파이썬"],
    short: "읽기 쉬운 문법으로 자동화, 데이터 처리, AI 등에 널리 쓰이는 언어.",
    analogy: "이야기꾼의 공책이다. 생각한 순서를 위에서 아래로 적으면 컴퓨터가 따라 읽는다.",
    useWhen: "기초 알고리즘, 파일 처리, 데이터 가공, 자동화 스크립트를 만들 때.",
    caution: "들여쓰기가 코드 구조다. 칸이 어긋나면 의미가 바뀐다.",
    related: ["변수", "함수", "리스트"],
    sources: ["Python", "CodeQuest"],
  },
  {
    term: "변수",
    category: "코딩 기본",
    aliases: ["variable", "값 상자"],
    short: "값에 이름을 붙여 다시 사용할 수 있게 하는 것.",
    analogy: "이름표가 붙은 작은 상자다.",
    useWhen: "숫자, 문자열, 계산 결과에 의미 있는 이름을 붙일 때.",
    caution: "이름은 내용이 보이게 짓고, 바뀌는 값인지 고정 값인지 구분한다.",
    related: ["값", "상수", "타입"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "함수",
    category: "코딩 기본",
    aliases: ["function", "def"],
    short: "이름을 붙여 재사용할 수 있는 코드 묶음.",
    analogy: "자동판매기다. 재료를 넣으면 정해진 방식으로 결과를 돌려준다.",
    useWhen: "같은 일을 여러 번 쓰거나 복잡한 일을 작게 나눌 때.",
    caution: "`return`과 출력은 다르다. 결과를 돌려줄지 화면에 보여줄지 구분한다.",
    related: ["매개변수", "return", "호출"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "조건문",
    category: "코딩 기본",
    aliases: ["if", "else", "branch"],
    short: "상황에 따라 다른 코드를 실행하게 하는 문법.",
    analogy: "갈림길의 신호등이다.",
    useWhen: "입력값, 점수, 잠금 상태에 따라 다른 결정을 내려야 할 때.",
    caution: "조건 순서가 중요하다. 넓은 조건을 먼저 쓰면 좁은 조건이 실행되지 않을 수 있다.",
    related: ["Boolean", "분기", "검증"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "반복문",
    category: "코딩 기본",
    aliases: ["loop", "for", "while"],
    short: "같은 규칙을 여러 값에 반복 적용하는 문법.",
    analogy: "우편배달부가 집집마다 같은 규칙으로 편지를 넣는 일이다.",
    useWhen: "목록, 숫자 범위, 여러 기록을 하나씩 처리할 때.",
    caution: "끝 조건이 틀리면 하나를 빼먹거나 너무 많이 반복한다.",
    related: ["리스트", "조건문", "누적"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "Boolean",
    category: "코딩 기본",
    aliases: ["불리언", "true/false"],
    short: "참 또는 거짓 둘 중 하나인 값.",
    analogy: "문이 열렸는지 닫혔는지만 알려주는 스위치다.",
    useWhen: "조건문, 잠금 상태, 성공 여부를 표현할 때.",
    caution: "문자열 \"false\"는 Boolean false와 다르다.",
    related: ["조건문", "상태", "검증"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "리스트/배열",
    category: "데이터와 비동기",
    aliases: ["list", "array"],
    short: "여러 값을 순서대로 담는 자료 구조.",
    analogy: "번호가 붙은 기차 칸이다.",
    useWhen: "이름 목록, 점수 목록, 미션 목록처럼 여러 항목을 다룰 때.",
    caution: "첫 번째 칸은 보통 0번이다.",
    related: ["반복문", "filter", "map"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "객체/딕셔너리",
    category: "데이터와 비동기",
    aliases: ["object", "dict", "dictionary"],
    short: "이름표와 값이 짝지어진 자료 구조.",
    analogy: "열쇠와 보물이 짝지어진 보관함이다.",
    useWhen: "사용자 정보, API 응답, 설정값처럼 속성 이름으로 값을 찾을 때.",
    caution: "없는 열쇠를 읽을 때 기본값이나 오류 처리를 생각한다.",
    related: ["JSON", "API", "속성"],
    sources: ["MDN", "Python", "CodeQuest"],
  },
  {
    term: "JSON",
    category: "데이터와 비동기",
    aliases: ["JavaScript Object Notation"],
    short: "문자열로 데이터를 주고받기 위한 표준 형식.",
    analogy: "다른 나라 사람도 읽을 수 있게 정해 둔 택배 송장 양식이다.",
    useWhen: "웹 API가 서버와 브라우저 사이에 데이터를 주고받을 때.",
    caution: "JSON 문자열은 객체가 아니다. JavaScript에서는 `JSON.parse`로 바꿔야 속성을 읽는다.",
    related: ["API", "객체/딕셔너리", "JSON.parse"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "filter",
    category: "데이터와 비동기",
    aliases: ["걸러내기"],
    short: "조건에 맞는 항목만 남기는 배열 처리.",
    analogy: "체로 모래를 털고 보석만 남기는 일이다.",
    useWhen: "통과한 학생, 완료된 미션, 검색 결과처럼 일부 항목만 보여줄 때.",
    caution: "조건이 반대로 쓰이면 필요한 항목을 버릴 수 있다.",
    related: ["map", "리스트/배열", "조건문"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "map",
    category: "데이터와 비동기",
    aliases: ["변환"],
    short: "각 항목을 다른 모양으로 바꾸는 배열 처리.",
    analogy: "모든 카드에 같은 형식의 이름표를 새로 붙이는 일이다.",
    useWhen: "객체 목록에서 이름만 꺼내거나 화면 카드 데이터로 바꿀 때.",
    caution: "map은 보통 항목 수를 그대로 유지한다. 줄이고 싶으면 filter가 먼저다.",
    related: ["filter", "리스트/배열", "React"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "reduce",
    category: "데이터와 비동기",
    aliases: ["누적", "fold"],
    short: "여러 값을 하나의 결과로 접어 모으는 처리.",
    analogy: "동전 여러 개를 저금통 하나에 모으는 일이다.",
    useWhen: "합계, 최대값, 통계처럼 목록을 한 값으로 요약할 때.",
    caution: "초기값을 명확히 주면 빈 배열과 타입 문제를 줄일 수 있다.",
    related: ["리스트/배열", "정렬", "누적"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "Promise",
    category: "데이터와 비동기",
    aliases: ["비동기 약속"],
    short: "나중에 성공하거나 실패할 값을 표현하는 JavaScript 객체.",
    analogy: "음식을 주문하고 받은 번호표다. 지금은 음식이 없지만 나중에 받을 약속이 있다.",
    useWhen: "API 호출, 파일 처리, AI 응답처럼 시간이 걸리는 작업을 다룰 때.",
    caution: "실패할 수 있으므로 에러 처리도 함께 생각한다.",
    related: ["async/await", "API", "JavaScript"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "async/await",
    category: "데이터와 비동기",
    aliases: ["비동기 기다림"],
    short: "Promise 결과를 순서대로 읽기 쉽게 기다리는 JavaScript 문법.",
    analogy: "번호표를 들고 기다리다가 음식이 나오면 다음 일을 하는 방식이다.",
    useWhen: "API 응답을 받은 뒤 그 결과로 화면이나 데이터를 바꿀 때.",
    caution: "`await`는 `async` 함수 안에서 쓰며, 실패 상황도 처리해야 한다.",
    related: ["Promise", "API", "JavaScript"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "Generator",
    category: "데이터와 비동기",
    aliases: ["제너레이터", "yield"],
    short: "값을 한꺼번에 만들지 않고 필요할 때 하나씩 내보내는 Python 개념.",
    analogy: "책을 통째로 들지 않고 한 장씩 넘겨 주는 창구다.",
    useWhen: "큰 데이터나 스트리밍처럼 조금씩 처리해야 할 때.",
    caution: "한 번 소비한 흐름은 다시 처음부터 읽을 수 없을 수 있다.",
    related: ["Python", "yield", "스트리밍"],
    sources: ["Python", "CodeQuest"],
  },
  {
    term: "React",
    category: "웹과 React",
    aliases: ["리액트", "UI 라이브러리"],
    short: "컴포넌트로 화면을 만들고 상태 변화에 따라 다시 그리는 UI 라이브러리.",
    analogy: "레고 블록으로 화면을 조립하는 도구다.",
    useWhen: "재사용 가능한 웹 화면 조각을 만들 때.",
    caution: "화면이 어디서 상태를 받고 어디서 바뀌는지 추적해야 한다.",
    related: ["Component", "Props", "State"],
    sources: ["React", "CodeQuest"],
  },
  {
    term: "Component",
    category: "웹과 React",
    aliases: ["컴포넌트", "화면 조각"],
    short: "React에서 재사용 가능한 UI 조각.",
    analogy: "레고 블록 하나다. 버튼, 카드, 지도 조각처럼 따로 만들고 조립한다.",
    useWhen: "같은 화면 패턴을 여러 곳에서 재사용할 때.",
    caution: "너무 큰 컴포넌트는 이해하기 어렵다. 책임을 작게 나눈다.",
    related: ["React", "Props", "JSX"],
    sources: ["React", "CodeQuest"],
  },
  {
    term: "Props",
    category: "웹과 React",
    aliases: ["properties", "전달값"],
    short: "부모 컴포넌트가 자식 컴포넌트에 전달하는 값.",
    analogy: "와플 기계에 넣는 반죽과 토핑이다. 기계는 같아도 재료가 다르면 결과가 다르다.",
    useWhen: "같은 컴포넌트를 다른 데이터로 보여줄 때.",
    caution: "자식은 props를 직접 바꾸기보다 받은 값으로 화면을 그린다.",
    related: ["Component", "State", "React"],
    sources: ["React", "CodeQuest"],
  },
  {
    term: "State",
    category: "웹과 React",
    aliases: ["상태", "내부 기억"],
    short: "컴포넌트나 앱이 현재 기억하고 있는 값.",
    analogy: "방의 전등 스위치다. 켜짐/꺼짐에 따라 방 모습이 달라진다.",
    useWhen: "클릭 횟수, 잠금 여부, 입력값처럼 변하는 화면 정보를 다룰 때.",
    caution: "상태가 어디서 바뀌는지 모르면 화면 버그를 찾기 어렵다.",
    related: ["Props", "Event", "Reducer"],
    sources: ["React", "CodeQuest"],
  },
  {
    term: "Event",
    category: "웹과 React",
    aliases: ["이벤트", "사용자 행동"],
    short: "클릭, 입력, 제출처럼 사용자나 시스템이 일으키는 신호.",
    analogy: "문을 두드리는 소리다. 소리가 나면 안에서 정해진 행동을 한다.",
    useWhen: "버튼 클릭이나 입력 변경에 반응해 상태를 바꿀 때.",
    caution: "이벤트 핸들러가 너무 많은 일을 하면 화면 흐름이 복잡해진다.",
    related: ["State", "React", "onClick"],
    sources: ["MDN", "React", "CodeQuest"],
  },
  {
    term: "Conditional rendering",
    category: "웹과 React",
    aliases: ["조건부 렌더링", "조건 화면"],
    short: "조건에 따라 어떤 화면을 보여줄지 고르는 React 패턴.",
    analogy: "무대 감독이 장면에 맞는 배우만 무대 위로 올리는 일이다.",
    useWhen: "잠금, 로딩, 오류, 힌트처럼 상태별 화면이 달라질 때.",
    caution: "보이지 않는 상태에서도 접근성이나 빈 화면 문제가 없는지 확인한다.",
    related: ["State", "Boolean", "Component"],
    sources: ["React", "CodeQuest"],
  },
  {
    term: "Import/Export",
    category: "웹과 React",
    aliases: ["모듈 가져오기", "내보내기"],
    short: "파일 사이에서 함수나 컴포넌트를 공유하는 문법.",
    analogy: "도서관에서 책을 꽂고 필요한 방에서 빌려 오는 규칙이다.",
    useWhen: "컴포넌트와 유틸 함수를 파일별로 나눠 재사용할 때.",
    caution: "기본 내보내기와 이름 내보내기를 섞으면 import 문이 틀리기 쉽다.",
    related: ["Component", "Module", "React"],
    sources: ["MDN", "React", "CodeQuest"],
  },
  {
    term: "API",
    category: "AI와 제품 품질",
    aliases: ["Application Programming Interface", "연결 규칙"],
    short: "프로그램끼리 정해진 방식으로 요청과 응답을 주고받는 약속.",
    analogy: "식당 주문서다. 정해진 칸에 메뉴를 적으면 주방이 결과를 내준다.",
    useWhen: "웹 앱이 서버, AI 모델, 외부 서비스와 통신할 때.",
    caution: "요청 형식, 인증, 오류 응답을 함께 다뤄야 한다.",
    related: ["JSON", "curl", "async/await"],
    sources: ["MDN", "App Factory", "CodeQuest"],
  },
  {
    term: "curl",
    category: "AI와 제품 품질",
    aliases: ["API 테스트 명령"],
    short: "터미널에서 URL로 요청을 보내고 응답을 확인하는 도구.",
    analogy: "웹 주소로 편지를 보내고 서버의 답장을 봉투째 읽는 도구다.",
    useWhen: "브라우저 없이 API 응답을 빠르게 확인할 때.",
    caution: "토큰이나 개인정보가 들어간 요청은 터미널 기록에 남을 수 있다.",
    related: ["API", "JSON", "터미널"],
    sources: ["MDN", "CodeQuest"],
  },
  {
    term: "Prompt",
    category: "AI와 제품 품질",
    aliases: ["프롬프트", "모델 지시문"],
    short: "AI 모델에게 원하는 역할, 입력, 출력 형식을 알려주는 지시문.",
    analogy: "요리사에게 주는 주문서다. 재료, 맛, 담는 방식을 자세히 적을수록 결과가 안정된다.",
    useWhen: "AI에게 코드 설명, 글쓰기, 데이터 변환, 검토를 맡길 때.",
    caution: "프롬프트만 믿지 말고 출력 검증, 개인정보, 안전 경계를 함께 설계한다.",
    related: ["AI Agent", "Spec", "Harness"],
    sources: ["App Factory", "CodeQuest"],
  },
  {
    term: "Spec",
    category: "AI와 제품 품질",
    aliases: ["스펙", "명세"],
    short: "무엇을 만들지, 어떻게 확인할지 적은 실행 기준.",
    analogy: "건물을 짓기 전 설계도와 검사표를 합친 문서다.",
    useWhen: "기능을 구현하기 전 목표, 범위, 테스트 기준을 맞출 때.",
    caution: "스펙이 모호하면 구현은 빨라 보여도 나중에 다시 만든다.",
    related: ["PRD", "Acceptance criteria", "Harness"],
    sources: ["App Factory", "MDN"],
  },
  {
    term: "Harness",
    category: "AI와 제품 품질",
    aliases: ["하네스", "실행 묶음"],
    short: "AI나 코드 생성기가 같은 기준으로 작업하도록 필요한 컨텍스트를 묶은 것.",
    analogy: "요리 대회 참가자에게 같은 재료 상자와 규칙서를 주는 일이다.",
    useWhen: "스펙, 제약, 예시, 산출물을 함께 전달해 재현 가능한 작업을 만들 때.",
    caution: "하네스가 오래되면 잘못된 기준을 반복한다. 최신 코드와 스펙으로 갱신한다.",
    related: ["Spec", "Prompt", "App Factory"],
    sources: ["App Factory"],
  },
  {
    term: "Acceptance criteria",
    category: "AI와 제품 품질",
    aliases: ["인수 기준", "통과 조건"],
    short: "기능이 완료됐다고 말할 수 있는 구체적인 조건.",
    analogy: "도장 받기 전 체크리스트다. 모두 맞아야 통과다.",
    useWhen: "미션, 기능, 릴리스가 정말 끝났는지 판단할 때.",
    caution: "눈으로 보기 좋다는 말보다 입력, 출력, 상태, 예외를 구체적으로 적는다.",
    related: ["Spec", "Test", "Release gate"],
    sources: ["App Factory", "CodeQuest"],
  },
  {
    term: "Test",
    category: "AI와 제품 품질",
    aliases: ["테스트", "검증"],
    short: "코드가 기대한 결과를 내는지 확인하는 절차.",
    analogy: "다리를 건너기 전에 모래주머니를 올려 보는 일이다.",
    useWhen: "새 기능, 버그 수정, 리팩터링 후 동작을 확인할 때.",
    caution: "테스트가 없으면 고친 줄 알았던 기능이 다시 깨질 수 있다.",
    related: ["Acceptance criteria", "Release gate", "Spec"],
    sources: ["App Factory", "CodeQuest"],
  },
  {
    term: "Release gate",
    category: "AI와 제품 품질",
    aliases: ["릴리스 게이트", "배포 관문"],
    short: "배포 전에 반드시 통과해야 하는 품질 검사.",
    analogy: "놀이기구를 열기 전 안전바, 전기, 안내문을 확인하는 최종 점검이다.",
    useWhen: "사용자에게 공개하기 전 빌드, 테스트, 접근성, 개인정보를 확인할 때.",
    caution: "게이트가 장식이면 위험하다. 실패하면 실제로 멈추도록 운영해야 한다.",
    related: ["Test", "Privacy", "A11y"],
    sources: ["App Factory", "CodeQuest"],
  },
  {
    term: "Privacy",
    category: "AI와 제품 품질",
    aliases: ["개인정보", "데이터 보호"],
    short: "사용자 정보가 불필요하게 수집, 노출, 공유되지 않게 지키는 원칙.",
    analogy: "친구의 일기장을 맡았을 때 잠금장치를 걸고 필요한 페이지만 보는 태도다.",
    useWhen: "로그인, 저장, 분석, AI 요청에 사용자 데이터가 들어갈 때.",
    caution: "민감 정보는 한번 공개되면 되돌리기 어렵다. 최소 수집과 명확한 안내가 필요하다.",
    related: ["Release gate", "API", "Prompt"],
    sources: ["App Factory", "CodeQuest"],
  },
  {
    term: "A11y",
    category: "AI와 제품 품질",
    aliases: ["접근성", "Accessibility"],
    short: "다양한 사용자가 앱을 이해하고 조작할 수 있게 만드는 품질 기준.",
    analogy: "계단만 있는 건물에 경사로와 안내판을 함께 두는 일이다.",
    useWhen: "버튼, 링크, 색상, 키보드 조작, 화면 읽기 지원을 설계할 때.",
    caution: "색만으로 상태를 구분하거나 이름 없는 버튼을 만들면 접근성이 깨진다.",
    related: ["Release gate", "UI", "Test"],
    sources: ["MDN", "App Factory", "CodeQuest"],
  },
];
