import type { Mission, TerminalChainStep } from "@/types/mission";

const EVER = { speaker: "대장장이 에버", emoji: "🔨" };
const CORY = { speaker: "전령 까치 코리", emoji: "🐦" };
const GREM = { speaker: "사고의 망령 그렘", emoji: "👻" };

const repoSeed = (
  root = "/quest/git-quest",
  extra: Record<string, string | null> = {},
  seed: Record<string, unknown> = {}
) => ({
  [root]: null,
  [`${root}/.git`]: null,
  [`${root}/README.md`]: "# Quest",
  [`${root}/.forge-git.json`]: JSON.stringify({
    root,
    commits: ["first"],
    ...seed,
  }),
  ...extra,
});

function chain(
  id: string,
  briefing: string,
  initialFs: Record<string, string | null>,
  initialCwd: string,
  objectives: TerminalChainStep["objectives"],
  hint?: string
): TerminalChainStep {
  return {
    id,
    kind: "terminal-chain",
    briefing,
    hint,
    initialFs,
    initialCwd,
    objectives,
  };
}

export const FORGE_MISSIONS: readonly Mission[] = [
  {
    id: "forge-01",
    realmId: "forge-of-origin",
    order: 1,
    title: "첫 발자국",
    fantasyTitle: "기원의 대장간 1장 — 「내가 선 곳」",
    summary: "Git을 배우기 전, 터미널에서 현재 위치를 확인한다.",
    isBoss: false,
    xpReward: 40,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["첫 단조는 망치가 아니라 발밑을 보는 것에서 시작한다.", "지금 네가 선 곳을 말해 보아라. 좌표를 아는 장인만 길을 잃지 않는다."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`pwd`로 현재 위치를 확인하라.",
        hint: "`pwd` 한 줄.",
        initialFs: { "/quest": null },
        initialCwd: "/quest",
        successWhen: { type: "commandUsed", command: "pwd" },
      },
      { id: "outro", kind: "dialogue", ...EVER, lines: ["좋다. 좌표를 아는 손은 다음 망치를 빗맞히지 않는다."] },
    ],
  },
  {
    id: "forge-02",
    realmId: "forge-of-origin",
    order: 2,
    title: "도장 만들기",
    fantasyTitle: "기원의 대장간 2장 — 「작업터를 세우라」",
    summary: "새 프로젝트 폴더를 만들고 그 안으로 이동한다.",
    isBoss: false,
    xpReward: 45,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["대장간은 아무 곳에나 세우지 않는다.", "작업터 `git-quest`를 만들고 그 안으로 들어가라."] },
      chain("challenge", "`git-quest` 디렉토리를 만들고 그 안으로 이동하라.", { "/quest": null }, "/quest", [
        { id: "mkdir", label: "작업터 만들기", commandPattern: "^mkdir\\s+git-quest$", successWhen: { type: "fsHasDir", path: "/quest/git-quest" }, hint: "`mkdir git-quest`" },
        { id: "cd", label: "작업터로 이동", commandPattern: "^cd\\s+git-quest$", successWhen: { type: "cwdEquals", path: "/quest/git-quest" }, hint: "`cd git-quest`" },
      ]),
      { id: "outro", kind: "dialogue", ...EVER, lines: ["좋다. 이제 이곳이 네 첫 저장소의 화로가 된다."] },
    ],
  },
  {
    id: "forge-03",
    realmId: "forge-of-origin",
    order: 3,
    title: "인장 확인",
    fantasyTitle: "기원의 대장간 3장 — 「도구와 신분」",
    summary: "Git 버전과 GitHub CLI 인증 상태를 확인한다.",
    isBoss: false,
    xpReward: 50,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["도구와 신분을 확인하자."] },
      { id: "cory", kind: "dialogue", ...CORY, lines: ["내 날개는 GitHub 신탁까지 닿아. `gh auth status`로 문이 열렸는지 보자!"] },
      chain("challenge", "`git -v`와 `gh auth status`를 순서대로 실행하라.", { "/quest/git-quest": null }, "/quest/git-quest", [
        { id: "git-version", label: "Git 도구 확인", commandPattern: "^git\\s+(-v|--version|version)$", successWhen: { type: "lastOutputMatches", pattern: "git version" }, hint: "`git -v`" },
        { id: "gh-auth", label: "GitHub 인증 확인", commandPattern: "^gh\\s+auth\\s+status$", successWhen: { type: "lastOutputMatches", pattern: "Logged in to github\\.com" }, hint: "`gh auth status`" },
      ]),
    ],
  },
  {
    id: "forge-04",
    realmId: "forge-of-origin",
    order: 4,
    title: "화로에 불 붙이기",
    fantasyTitle: "기원의 대장간 4장 — 「시간 화로」",
    summary: "현재 폴더를 Git 저장소로 초기화한다.",
    isBoss: false,
    xpReward: 60,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["이 화로는 시간을 담는다.", "처음 불을 붙일 때는 중심 가지의 이름을 `main`으로 새겨라."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`git init -b main`으로 저장소를 초기화하라.",
        hint: "`git init -b main`",
        initialFs: { "/quest/git-quest": null },
        initialCwd: "/quest/git-quest",
        successWhen: { type: "gitRepoInitialized", at: "/quest/git-quest" },
      },
    ],
  },
  {
    id: "forge-05",
    realmId: "forge-of-origin",
    order: 5,
    title: "첫 광물 캐기",
    fantasyTitle: "기원의 대장간 5장 — 「README 원석」",
    summary: "README 파일을 만들어 첫 기록을 남긴다.",
    isBoss: false,
    xpReward: 55,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["첫 광물은 기록이다.", "README는 장인이 남기는 첫 표식이다."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`echo \"# Quest\" > README.md`로 README를 만들어라.",
        hint: "`echo \"# Quest\" > README.md`",
        initialFs: { "/quest/git-quest": null },
        initialCwd: "/quest/git-quest",
        successWhen: { type: "fsHasFile", path: "/quest/git-quest/README.md" },
      },
    ],
  },
  {
    id: "forge-06",
    realmId: "forge-of-origin",
    order: 6,
    title: "빨간 불·초록 불",
    fantasyTitle: "기원의 대장간 6장 — 「스테이지 위로」",
    summary: "git status와 git add로 untracked 파일을 staged 상태로 바꾼다.",
    isBoss: false,
    xpReward: 70,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["빨간 광물은 아직 화로 밖에 있다. 초록 광물만 단조된다.", "상태를 보고, README를 올리고, 다시 상태를 보아라."] },
      chain("challenge", "`status → add → status` 순서로 README를 stage에 올려라.", repoSeed("/quest/git-quest", {}, { commits: [] }), "/quest/git-quest", [
        { id: "status-red", label: "빨간 상태 보기", commandPattern: "^git\\s+status$", successWhen: { type: "lastOutputMatches", pattern: "Untracked files" }, hint: "`git status`" },
        { id: "add", label: "README 올리기", commandPattern: "^git\\s+add\\s+README\\.md$", successWhen: { type: "gitStagedFile", file: "README.md" }, hint: "`git add README.md`" },
        { id: "status-green", label: "초록 상태 확인", commandPattern: "^git\\s+status$", successWhen: { type: "lastOutputMatches", pattern: "Changes to be committed" }, hint: "`git status`" },
      ]),
    ],
  },
  {
    id: "forge-07",
    realmId: "forge-of-origin",
    order: 7,
    title: "첫 단조",
    fantasyTitle: "기원의 대장간 7장 — 「첫 커밋」",
    summary: "staged 파일을 커밋하고 로그에서 확인한다.",
    isBoss: false,
    xpReward: 80,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["커밋은 되돌아갈 수 있는 시간의 못이다.", "메시지를 붙여 박고, 일지를 펼쳐 확인하라."] },
      chain("challenge", "README를 올리고 커밋한 뒤 `git log`로 확인하라.", repoSeed("/quest/git-quest", {}, { commits: [] }), "/quest/git-quest", [
        { id: "add", label: "README 올리기", commandPattern: "^git\\s+add\\s+README\\.md$", successWhen: { type: "gitStagedFile", file: "README.md" }, hint: "`git add README.md`" },
        { id: "commit", label: "첫 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 1 }, hint: "`git commit -m \"first\"`" },
        { id: "log", label: "일지 확인", commandPattern: "^git\\s+log$", successWhen: { type: "lastOutputMatches", pattern: "first" }, hint: "`git log`" },
      ]),
    ],
  },
  {
    id: "forge-boss-1",
    realmId: "forge-of-origin",
    order: 8,
    title: "그렘의 첫 시험",
    fantasyTitle: "보스 1 — 「망각의 add」",
    summary: "파일 하나만 add한 실수를 확인하고, 누락 파일을 별도 커밋으로 복구한다.",
    isBoss: true,
    xpReward: 120,
    steps: [
      { id: "boss-enter", kind: "dialogue", ...GREM, lines: ["하나만 올리고 둘 다 단조했다고 착각했지?", "네 두 번째 광물은 아직 차가운 바닥에 있다."] },
      { id: "ever", kind: "dialogue", ...EVER, lines: ["실패를 보아라. 누락된 파일은 따로 구하면 된다."] },
      chain("challenge", "README와 setup.py 중 README만 먼저 커밋한 뒤, setup.py를 두 번째 커밋으로 복구하라.", repoSeed("/quest/git-quest", { "/quest/git-quest/setup.py": "print('setup')" }, { commits: [] }), "/quest/git-quest", [
        { id: "add-readme", label: "README만 올리기", commandPattern: "^git\\s+add\\s+README\\.md$", successWhen: { type: "gitStagedFile", file: "README.md" }, hint: "`git add README.md`" },
        { id: "commit-one", label: "첫 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 1 }, hint: "`git commit -m \"readme\"`" },
        { id: "add-setup", label: "누락 파일 올리기", commandPattern: "^git\\s+add\\s+setup\\.py$", successWhen: { type: "gitStagedFile", file: "setup.py" }, hint: "`git add setup.py`" },
        { id: "commit-two", label: "복구 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 2 }, hint: "`git commit -m \"add setup\"`" },
      ]),
    ],
  },
  {
    id: "forge-08",
    realmId: "forge-of-origin",
    order: 9,
    title: "신탁과 악수",
    fantasyTitle: "기원의 대장간 8장 — 「repo 권한」",
    summary: "GitHub CLI 인증 scope 문제를 확인하고 repo 권한을 추가한다.",
    isBoss: false,
    xpReward: 80,
    steps: [
      { id: "intro", kind: "dialogue", ...CORY, lines: ["하늘다리는 허가받은 전령만 지난다.", "지금 네 인장에는 `repo` 권한이 빠져 있어. 새겨 넣자."] },
      chain("challenge", "`gh auth status`로 scope를 확인하고 `repo` scope를 추가하라.", repoSeed(), "/quest/git-quest", [
        { id: "status", label: "현재 scope 확인", commandPattern: "^gh\\s+auth\\s+status$", successWhen: { type: "lastOutputMatches", pattern: "Token scopes" }, hint: "`gh auth status`" },
        { id: "refresh", label: "repo scope 추가", commandPattern: "^gh\\s+auth\\s+refresh\\s+--scopes\\s+repo$", successWhen: { type: "ghAuthScopeIncludes", scope: "repo" }, hint: "`gh auth refresh --scopes repo`" },
      ]),
    ],
  },
  {
    id: "forge-09",
    realmId: "forge-of-origin",
    order: 10,
    title: "하늘다리 놓기",
    fantasyTitle: "기원의 대장간 9장 — 「origin 생성」",
    summary: "GitHub 원격 저장소를 만들고 origin remote를 연결한다.",
    isBoss: false,
    xpReward: 90,
    steps: [
      { id: "intro", kind: "dialogue", ...CORY, lines: ["이제 원격 보관소를 세운다.", "대장간의 이름을 그대로 하늘 아카이브에 걸어라."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`gh repo create git-quest --public --source=. --remote=origin`을 실행하라.",
        hint: "권한은 이미 준비되어 있다.",
        initialFs: repoSeed("/quest/git-quest", {}, { scopes: ["repo"] }),
        initialCwd: "/quest/git-quest",
        successWhen: { type: "gitRemoteExists", name: "origin" },
      },
    ],
  },
  {
    id: "forge-10",
    realmId: "forge-of-origin",
    order: 11,
    title: "첫 푸시",
    fantasyTitle: "기원의 대장간 10장 — 「하늘로 보내라」",
    summary: "첫 커밋을 origin/main으로 push한다.",
    isBoss: false,
    xpReward: 90,
    steps: [
      { id: "intro", kind: "dialogue", ...CORY, lines: ["두루마리를 하늘다리로 보내라!", "처음 길은 `-u`로 기억시켜 둔다."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`git push -u origin main`으로 첫 커밋을 올려라.",
        hint: "`git push -u origin main`",
        initialFs: repoSeed("/quest/git-quest", {}, { scopes: ["repo"], remotes: { origin: "https://github.com/Reasonofmoon/git-quest.git" } }),
        initialCwd: "/quest/git-quest",
        successWhen: { type: "gitLastPush", remote: "origin", branch: "main" },
      },
    ],
  },
  {
    id: "forge-11",
    realmId: "forge-of-origin",
    order: 12,
    title: "평행우주 가르기",
    fantasyTitle: "기원의 대장간 11장 — 「feature-bio」",
    summary: "새 브랜치를 만들고 그 브랜치로 이동한다.",
    isBoss: false,
    xpReward: 80,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["새 시도는 본류를 더럽히지 않는 가지에서 한다.", "feature-bio라는 평행 길을 열어라."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`git switch -c feature-bio`를 실행하라.",
        hint: "`git switch -c feature-bio`",
        initialFs: repoSeed(),
        initialCwd: "/quest/git-quest",
        successWhen: { type: "gitCurrentBranch", name: "feature-bio" },
      },
    ],
  },
  {
    id: "forge-12",
    realmId: "forge-of-origin",
    order: 13,
    title: "두 우주의 합",
    fantasyTitle: "기원의 대장간 12장 — 「깨끗한 merge」",
    summary: "feature 브랜치를 main에 병합한다.",
    isBoss: false,
    xpReward: 90,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["좋은 가지는 다시 본류에 합쳐진다.", "main으로 돌아와 가지의 결과를 병합하라."] },
      chain("challenge", "`main`으로 돌아와 `feature-bio`를 병합하라.", repoSeed("/quest/git-quest", {}, { branch: "feature-bio", commits: ["first", "bio"] }), "/quest/git-quest", [
        { id: "switch-main", label: "main으로 복귀", commandPattern: "^git\\s+switch\\s+main$", successWhen: { type: "gitCurrentBranch", name: "main" }, hint: "`git switch main`" },
        { id: "merge", label: "feature-bio 병합", commandPattern: "^git\\s+merge\\s+feature-bio$", successWhen: { type: "lastOutputMatches", pattern: "Fast-forward" }, hint: "`git merge feature-bio`" },
      ]),
    ],
  },
  {
    id: "forge-boss-2",
    realmId: "forge-of-origin",
    order: 14,
    title: "그렘의 충돌 함정",
    fantasyTitle: "보스 2 — 「같은 줄의 두 운명」",
    summary: "merge conflict를 만들고 충돌 마커를 제거해 해결 커밋을 남긴다.",
    isBoss: true,
    xpReward: 140,
    steps: [
      { id: "boss-enter", kind: "dialogue", ...GREM, lines: ["같은 줄에 두 운명을 새기면 어느 쪽이 진짜냐?", "충돌 표식 속에서 길을 잃어라!"] },
      { id: "ever", kind: "dialogue", ...EVER, lines: ["충돌 표식을 지우고 네 손으로 하나의 문장을 택하라."] },
      chain("challenge", "conflict-bio 브랜치를 병합해 충돌을 만든 뒤, bio.md를 정리하고 해결 커밋을 남겨라.", repoSeed("/quest/git-quest", { "/quest/git-quest/bio.md": "main version" }, { commits: ["first"] }), "/quest/git-quest", [
        { id: "branch", label: "충돌 브랜치 열기", commandPattern: "^git\\s+switch\\s+-c\\s+conflict-bio$", successWhen: { type: "gitCurrentBranch", name: "conflict-bio" }, hint: "`git switch -c conflict-bio`" },
        { id: "branch-edit", label: "브랜치 내용 수정", commandPattern: "^echo\\s+.+>\\s*bio\\.md$", successWhen: { type: "fsHasFile", path: "/quest/git-quest/bio.md" }, hint: "`echo \"branch version\" > bio.md`" },
        { id: "branch-commit", label: "브랜치 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 2 }, hint: "`git add bio.md && git commit -m \"branch bio\"`" },
        { id: "main", label: "main으로 복귀", commandPattern: "^git\\s+switch\\s+main$", successWhen: { type: "gitCurrentBranch", name: "main" }, hint: "`git switch main`" },
        { id: "main-commit", label: "main 수정 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 3 }, hint: "`echo \"main version\" > bio.md && git add bio.md && git commit -m \"main bio\"`" },
        { id: "merge", label: "충돌 발생 확인", commandPattern: "^git\\s+merge\\s+conflict-bio$", successWhen: { type: "lastOutputMatches", pattern: "CONFLICT" }, hint: "`git merge conflict-bio`" },
        { id: "resolve", label: "충돌 해결 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitMergeResolved", file: "bio.md" }, hint: "`echo \"resolved bio\" > bio.md && git add bio.md && git commit -m \"resolve conflict\"`" },
      ]),
    ],
  },
  {
    id: "forge-13",
    realmId: "forge-of-origin",
    order: 15,
    title: "봉인의 두루마리",
    fantasyTitle: "기원의 대장간 13장 — 「.gitignore」",
    summary: "추적하면 안 되는 파일을 .gitignore로 제외한다.",
    isBoss: false,
    xpReward: 80,
    steps: [
      { id: "intro", kind: "dialogue", ...EVER, lines: ["모든 물건을 화로에 넣는 장인은 없다.", "무거운 짐과 비밀 인장을 `.gitignore`의 문밖에 세워라."] },
      chain("challenge", "`.gitignore`에 `node_modules/`를 쓰고 커밋하라.", repoSeed(), "/quest/git-quest", [
        { id: "write", label: ".gitignore 작성", commandPattern: "^echo\\s+.+>\\s*\\.gitignore$", successWhen: { type: "fsHasFile", path: "/quest/git-quest/.gitignore" }, hint: "`echo \"node_modules/\" > .gitignore`" },
        { id: "add", label: ".gitignore 올리기", commandPattern: "^git\\s+add\\s+\\.gitignore$", successWhen: { type: "gitStagedFile", file: ".gitignore" }, hint: "`git add .gitignore`" },
        { id: "commit", label: "봉인 커밋", commandPattern: "^git\\s+commit\\s+-m\\s+.+", successWhen: { type: "gitCommitCount", min: 2 }, hint: "`git commit -m \"add gitignore\"`" },
      ]),
    ],
  },
  {
    id: "forge-14",
    realmId: "forge-of-origin",
    order: 16,
    title: "풀 리퀘스트",
    fantasyTitle: "기원의 대장간 14장 — 「검토의 문」",
    summary: "GitHub CLI로 Pull Request를 만든다.",
    isBoss: false,
    xpReward: 90,
    steps: [
      { id: "intro", kind: "dialogue", ...CORY, lines: ["혼자 합치지 말고 검토의 문을 두드려!", "제목과 설명을 담은 PR 두루마리를 올려라."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`gh pr create --title \"bio\" --body \"add bio\"`로 PR을 생성하라.",
        hint: "`gh pr create --title \"bio\" --body \"add bio\"`",
        initialFs: repoSeed("/quest/git-quest", {}, { branch: "feature-bio", commits: ["first", "bio"], remotes: { origin: "https://github.com/Reasonofmoon/git-quest.git" }, scopes: ["repo"] }),
        initialCwd: "/quest/git-quest",
        successWhen: { type: "lastOutputMatches", pattern: "https://github\\.com/.+/pull/\\d+" },
      },
    ],
  },
  {
    id: "forge-15",
    realmId: "forge-of-origin",
    order: 17,
    title: "신탁의 봉인",
    fantasyTitle: "기원의 대장간 15장 — 「merge and delete」",
    summary: "Pull Request를 병합하고 사용한 브랜치를 정리한다.",
    isBoss: false,
    xpReward: 90,
    steps: [
      { id: "intro", kind: "dialogue", ...CORY, lines: ["검토가 끝났다. 봉인을 닫자."] },
      { id: "ever", kind: "dialogue", ...EVER, lines: ["병합하고 다 쓴 가지는 정리해라."] },
      {
        id: "challenge",
        kind: "terminal",
        briefing: "`gh pr merge --merge --delete-branch`로 PR을 병합하라.",
        hint: "`gh pr merge --merge --delete-branch`",
        initialFs: repoSeed("/quest/git-quest", {}, { branch: "feature-bio", commits: ["first", "bio"], scopes: ["repo"], prs: [{ title: "bio", branch: "feature-bio", merged: false }] }),
        initialCwd: "/quest/git-quest",
        successWhen: { type: "ghPrMerged" },
      },
    ],
  },
  {
    id: "forge-boss-3",
    realmId: "forge-of-origin",
    order: 18,
    title: "그렘의 최후",
    fantasyTitle: "최종 보스 — 「잘못된 화로」",
    summary: "홈 디렉토리에 잘못 만든 .git을 제거하고 올바른 폴더에서 다시 초기화한다.",
    isBoss: true,
    xpReward: 180,
    steps: [
      { id: "boss-enter", kind: "dialogue", ...GREM, lines: ["하하! 네 집 전체가 빨갛게 타오른다!", "`.ssh`, `.zshrc`, `Documents`까지 전부 빨간 불이다!"] },
      { id: "ever", kind: "dialogue", ...EVER, lines: ["멈춰라. 잘못 붙인 화로는 그 자리에서 꺼야 한다.", "상위 `.git`을 제거하고, 올바른 작업터에서 다시 시작하라."] },
      chain("challenge", "일부러 홈에서 잘못 초기화한 뒤, 위험한 `.git`을 제거하고 `/quest/git-quest`에서 다시 초기화하라.", { "/quest": null, "/quest/git-quest": null, "/.ssh/id_rsa": "PRIVATE", "/.zshrc": "alias gs='git status'", "/Documents/tax.txt": "secret" }, "/quest/git-quest", [
        { id: "home", label: "홈으로 이동", commandPattern: "^cd\\s+~$", successWhen: { type: "cwdEquals", path: "/" }, hint: "`cd ~`" },
        { id: "bad-init", label: "잘못된 위치에서 init", commandPattern: "^git\\s+init\\s+-b\\s+main$", successWhen: { type: "gitRepoInitialized", at: "/" }, hint: "`git init -b main`" },
        { id: "danger-status", label: "위험 상태 확인", commandPattern: "^git\\s+status$", successWhen: { type: "lastOutputMatches", pattern: "\\.ssh|\\.zshrc|Documents" }, hint: "`git status`" },
        { id: "remove", label: "잘못된 .git 철거", commandPattern: "^rm\\s+-rf\\s+\\.git$", successWhen: { type: "gitNoRepoAt", at: "/" }, hint: "`rm -rf .git`" },
        { id: "return", label: "작업터 복귀", commandPattern: "^cd\\s+/quest/git-quest$", successWhen: { type: "cwdEquals", path: "/quest/git-quest" }, hint: "`cd /quest/git-quest`" },
        { id: "good-init", label: "올바른 위치에서 init", commandPattern: "^git\\s+init\\s+-b\\s+main$", successWhen: { type: "all", checks: [{ type: "gitRepoInitialized", at: "/quest/git-quest" }, { type: "gitNoRepoAt", at: "/" }] }, hint: "`git init -b main`" },
      ]),
    ],
  },
];
